### ISSUE TITLE
Production Builds MVP

### ISSUE THREAD

**Issue by wycats** [starbeamjs/starbeam#1]
We should make it easy to strip out runtime behavior that is only there for debug purposes.

## Things to do:

- [x] Integrate the [import.meta.env] Vite de facto standard
- [x] Use conditionals to remove as much behavior as possible
- [ ] Ship a `debug` entry point with debug features in and a `prod` entry point with debug features out
- [ ] Figure out and document how to automate the use of the correct entry point in popular bundlers
- [ ] Figure out how to make loose modules "just work" with downstream Vite users

## Out of scope for this issue:

- Figure out how to minimize the code size of unused production features.

This is important, but it's a little trickier, because it involves things like stripping out unused methods, which has implications for TypeScript. My preferred solution is to use build-time decorators with `import.meta.env` to remove unused behavior.

- Transform the `verify` pattern (`verify(expr, isPresent)`) to remove the call to verify entirely.

This is *very* important, but requires a different kind of work than the primary work this ticket is about.

Both of these are important near-term follow-up issues.

[import.meta.env]: https://vitejs.dev/guide/env-and-mode.html

**Comment by NullVoxPopuli** [comment]
Here is a PR that tries to use what's on `main`: https://github.com/NullVoxPopuli/latency-tester/pull/9

We can use this to test out production mode: 

At the time of writing, we still have:
- inspect-utils
- stacktracey
- some lingering `import.meta.env.DEV`
- nydus?
![image](https://github.com/starbeamjs/starbeam/assets/199018/c526dbf4-8785-4a9b-ad1e-fd8a3fa3e606)

**Comment by wycats** [comment]
Closing this out as the effort to identify a solid production build strategy is now happening in https://github.com/starbeamjs/starbeam-lite. That repo is a testbed for addressing some of the long-standing open questions in the Starbeam fundamentals. Once we get to the end of that exploration, this repo will and starbeam-lite will be merged.
